### ISSUE TITLE
sérti a naming convention-t az elnevezés módja

### ISSUE THREAD

**Issue by netdjw** [Oraveczgergo/Webprog#17]
https://github.com/Oraveczgergo/Webprog/blob/cafc2d9f6ab8740e7703cee28d483db3c6ebda4b/javascript.js#L183

A funkció elnevezése sérti azt a naming convention-t, hogy a funkciók nevei camel case módon legyenek elnevezve, az osztályok pedig title case módon.

- https://en.wikipedia.org/wiki/Naming_convention
- https://en.wikipedia.org/wiki/Naming_convention_(programming)
- https://www.crockford.com/code.html

**Comment by Oraveczgergo** [comment]
Elnevezés javítva.
