### ISSUE TITLE
A sorok kirajzolása programozottan történjen

### ISSUE THREAD

**Issue by netdjw** [Oraveczgergo/Webprog#4]
Jelenleg bele van kódolva, hogy 10 lehetőség van tippelni. Így a HTML kód módosítása nélkül nem áll fenn a lehetősége annak, hogy módosítsam a program beállításait.

Valahol 1 helyen legyen definiálva, hogy mennyi sort mutat a program és annyiszor engedjen a program tippet leadni, ahány sor van. Ha átírom ezt az 1 értéket 20-ra akkor képes legyen kezelni ezt is a többi kód módosítása nélkül.

**Comment by Oraveczgergo** [comment]
A sorokat mostmár a js generálja
