### ISSUE TITLE
Szín megnevezések javítása

### ISSUE THREAD

**Issue by netdjw** [Oraveczgergo/Webprog#5]
Jelengeg az elnevezések eléggé beszédesek a színekkel kapcsolatban, egyúttal viszont bele is van kódolva a programba, hogy milyen színt kell tartalmazzon az adott dolog. Pl. egy div. De ha a CSS-ben átírom az osztály színkódját, akkor már nem lesz egyértelmű.

Ezért át kell alakítani az elnevezési rendszert úgy, hogy az ne függjön attól, hogy a változókban, CSS-ben milyen értékek vannak definiálva.

**Comment by Oraveczgergo** [comment]
Szín megnevezések kijavítva
