### ISSUE TITLE
a kód ellátása kommentekkel

### ISSUE THREAD

**Issue by netdjw** [Oraveczgergo/Webprog#7]
A legjobb az lenne, ha soronként, de legalább kód egységenként dokumentálva lenne, hogy mit csinál a program.

https://jsdoc.app/

Itt van bővebb doksi arról, hgy a JSDoc hogyan működik.

**Comment by Oraveczgergo** [comment]
Elláttam a kódot JSDoc kommentekkel. Igyekeztem értelmesen dokumentálni a működését.
