### ISSUE TITLE
JS kódból HTML kód eltüntetése

### ISSUE THREAD

**Issue by netdjw** [Oraveczgergo/Webprog#8]
Az efféle megoldások bár működnek, de bad-practice megoldások:

```javascript
guess += "<div class=\"cell\" style=\"background-color: red;\"></div>";
```

Helyette tisztán JS kóddal legyen megoldva.

Kapcsolódó doksi:
- https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
- https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style
- https://developer.mozilla.org/en-US/docs/Web/API/Element/className
- https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Comment by Oraveczgergo** [comment]
Html kód eltüntetve a Javascript fájlból.
